export enum ConfigKeyEnum {
  PORT = 'PORT',
  MONGO_URI = 'MONGO_URI',
  GOOGLE_PUBSUB_PROJECT_ID = 'GOOGLE_PUBSUB_PROJECT_ID',
  GOOGLE_PUB_SUB_API_ENDPOINT = 'GOOGLE_PUB_SUB_API_ENDPOINT',
  SERVICE_ID = 'SERVICE_ID',
}
